import type { Metadata } from "next";
import LegalLayout from "@/components/legal/LegalLayout";
import { SITE } from "@/lib/constants";

export const metadata: Metadata = {
  title: "Terms of Use",
  description: `Terms of Use for the ${SITE.name} application and services.`,
  alternates: { canonical: `${SITE.url}/terms` },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  name: `Terms of Use — ${SITE.name}`,
  url: `${SITE.url}/terms`,
  breadcrumb: {
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: "Home",
        item: SITE.url,
      },
      {
        "@type": "ListItem",
        position: 2,
        name: "Terms of Use",
        item: `${SITE.url}/terms`,
      },
    ],
  },
};

export default function TermsOfUse() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <LegalLayout title="Terms of Use" lastUpdated="February 5, 2026">
        <p>
          Welcome to Verbio. These Terms of Use (&quot;Terms&quot;) govern your
          access to and use of the Verbio mobile application (&quot;App&quot;),
          website located at{" "}
          <a href={SITE.url}>{SITE.url}</a> (&quot;Website&quot;), and all
          related services (collectively, the &quot;Service&quot;) provided by{" "}
          {SITE.companyName} (&quot;Verbio,&quot; &quot;we,&quot;
          &quot;us,&quot; or &quot;our&quot;).
        </p>
        <p>
          By downloading, installing, or using the App, or by accessing the
          Website, you agree to be bound by these Terms. If you do not agree
          to these Terms, do not use the Service.
        </p>

        <h2 id="eligibility">1. Eligibility</h2>
        <p>
          You must be at least 13 years of age to use the Service. If you are
          between 13 and 18 years of age (or the age of legal majority in your
          jurisdiction), you may only use the Service with the consent of a
          parent or legal guardian who agrees to be bound by these Terms.
        </p>
        <p>
          By using the Service, you represent and warrant that you meet these
          eligibility requirements and have the legal capacity to enter into
          these Terms.
        </p>

        <h2 id="account">2. Account Registration</h2>
        <p>
          To access certain features of the Service, you must create an
          account using Sign in with Apple. You agree to provide accurate,
          current, and complete information and to maintain the security of
          your account credentials. You are responsible for all activity that
          occurs under your account.
        </p>
        <p>
          You agree to notify us immediately of any unauthorized access to or
          use of your account. We reserve the right to suspend or terminate
          your account if we reasonably believe that unauthorized access has
          occurred.
        </p>

        <h2 id="service">3. Description of Service</h2>
        <p>
          Verbio provides AI-powered voice translation services that enable
          users to translate spoken language across 50+ languages. The Service
          includes:
        </p>
        <ul>
          <li>Voice-to-voice translation in real time</li>
          <li>Two-way conversation translation mode</li>
          <li>Text display of translations</li>
          <li>Phrase saving and management</li>
          <li>Offline translation capabilities (Premium subscribers)</li>
        </ul>
        <p>
          Translation results are generated by artificial intelligence and may
          not always be perfectly accurate. The Service is intended as a
          communication aid and should not be relied upon for critical
          translations where errors could result in harm, including but not
          limited to medical, legal, or emergency communications.
        </p>

        <h2 id="subscriptions">4. Subscriptions and Billing</h2>

        <h3>4.1 Free Tier</h3>
        <p>
          The Service offers a free tier with limited features, including 10
          translations per day and 10 minutes of audio translation per month.
          The free tier may be modified or discontinued at any time.
        </p>

        <h3>4.2 Paid Subscriptions</h3>
        <p>
          Verbio offers the following subscription plans:
        </p>
        <ul>
          <li>
            <strong>Pro</strong> &mdash; $4.99/month or $39.99/year: 200
            translations per day, 300 minutes per month, premium voices,
            conversation mode, and phrase saving.
          </li>
          <li>
            <strong>Premium</strong> &mdash; $9.99/month or $79.99/year:
            Unlimited translations, unlimited minutes, all voices, offline
            mode, and priority processing.
          </li>
        </ul>

        <h3>4.3 Payment Processing</h3>
        <p>
          All payments are processed through Apple&apos;s App Store. By
          purchasing a subscription, you agree to Apple&apos;s{" "}
          <a
            href="https://www.apple.com/legal/internet-services/itunes/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Terms and Conditions
          </a>
          . We do not directly collect, store, or process your payment
          information.
        </p>

        <h3>4.4 Auto-Renewal</h3>
        <p>
          Subscriptions automatically renew at the end of each billing period
          (monthly or annually) unless you cancel at least 24 hours before the
          end of the current period. Your Apple ID account will be charged for
          renewal within 24 hours prior to the end of the current period at
          the rate of the selected plan.
        </p>

        <h3>4.5 Free Trials</h3>
        <p>
          Yearly subscription plans may include a 7-day free trial. If you
          cancel during the free trial period, you will not be charged. If you
          do not cancel, your subscription will automatically begin and your
          Apple ID account will be charged at the end of the trial period. A
          free trial may only be used once per Apple ID.
        </p>

        <h3>4.6 Cancellation</h3>
        <p>
          You may cancel your subscription at any time through your Apple ID
          account settings or within the App under Settings &gt; Subscription
          &gt; Manage Subscription. Upon cancellation, you will retain access
          to your subscription features until the end of the current billing
          period. No refunds or credits will be provided for partial billing
          periods.
        </p>

        <h3>4.7 Refunds</h3>
        <p>
          All refund requests are handled by Apple in accordance with
          Apple&apos;s refund policies. To request a refund, visit{" "}
          <a
            href="https://reportaproblem.apple.com"
            target="_blank"
            rel="noopener noreferrer"
          >
            reportaproblem.apple.com
          </a>
          .
        </p>

        <h3>4.8 Price Changes</h3>
        <p>
          We reserve the right to change subscription prices at any time. If
          we change prices, we will provide notice through the App or by other
          means. Price changes will apply to the next billing period after the
          change. Your continued use of the Service after a price change
          constitutes acceptance of the new pricing.
        </p>

        <h2 id="conduct">5. User Conduct</h2>
        <p>You agree not to use the Service to:</p>
        <ul>
          <li>Violate any applicable law, regulation, or third-party right</li>
          <li>
            Transmit or translate content that is unlawful, defamatory,
            harassing, abusive, threatening, or invasive of another&apos;s
            privacy
          </li>
          <li>
            Impersonate any person or entity, or misrepresent your affiliation
            with any person or entity
          </li>
          <li>
            Attempt to reverse engineer, decompile, disassemble, or otherwise
            derive source code from the App
          </li>
          <li>
            Use automated systems, bots, or scripts to access the Service in a
            manner that exceeds reasonable use
          </li>
          <li>
            Interfere with or disrupt the Service or servers or networks
            connected to the Service
          </li>
          <li>
            Use the Service for any purpose that is critical to personal
            safety, including emergency services, medical diagnoses, or legal
            proceedings, without independent verification
          </li>
        </ul>

        <h2 id="ip">6. Intellectual Property</h2>
        <p>
          The Service, including the App, Website, and all content, features,
          and functionality (including but not limited to all information,
          software, text, displays, images, audio, and the design, selection,
          and arrangement thereof) are owned by {SITE.companyName}, its
          licensors, or other providers of such material and are protected by
          United States and international copyright, trademark, patent, trade
          secret, and other intellectual property or proprietary rights laws.
        </p>
        <p>
          &quot;Verbio,&quot; the Verbio logo, and all related names, logos,
          product and service names, designs, and slogans are trademarks of{" "}
          {SITE.companyName}. You must not use such marks without our prior
          written permission.
        </p>

        <h2 id="user-content">7. User Content</h2>
        <p>
          Audio recordings and text that you submit for translation
          (&quot;User Content&quot;) remain your property. By using the
          Service, you grant us a limited, non-exclusive, royalty-free license
          to process your User Content solely for the purpose of providing the
          Service, including translation and speech synthesis.
        </p>
        <p>
          We do not store your audio recordings after processing unless you
          explicitly save translations to your phrase library. Saved phrases
          are stored securely and associated with your account.
        </p>

        <h2 id="third-party">8. Third-Party Services</h2>
        <p>
          The Service may integrate with or rely on third-party services,
          including but not limited to AI model providers, cloud
          infrastructure, and Apple&apos;s authentication and payment systems.
          Your use of such third-party services is subject to their respective
          terms and conditions. We are not responsible for the practices or
          policies of any third-party services.
        </p>

        <h2 id="disclaimers">9. Disclaimers</h2>
        <p>
          THE SERVICE IS PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS
          AVAILABLE&quot; BASIS, WITHOUT ANY WARRANTIES OF ANY KIND, EITHER
          EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF
          MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT,
          OR ACCURACY.
        </p>
        <p>
          WE DO NOT WARRANT THAT TRANSLATIONS WILL BE ACCURATE, COMPLETE, OR
          ERROR-FREE. AI-GENERATED TRANSLATIONS MAY CONTAIN ERRORS,
          INACCURACIES, OR INAPPROPRIATE CONTENT. YOU USE THE SERVICE AT YOUR
          OWN RISK.
        </p>
        <p>
          WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, TIMELY,
          SECURE, OR ERROR-FREE, OR THAT DEFECTS WILL BE CORRECTED.
        </p>

        <h2 id="liability">10. Limitation of Liability</h2>
        <p>
          TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT
          SHALL {SITE.companyName.toUpperCase()}, ITS AFFILIATES, OFFICERS,
          DIRECTORS, EMPLOYEES, AGENTS, SUPPLIERS, OR LICENSORS BE LIABLE FOR
          ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE
          DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE,
          GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM:
        </p>
        <ul>
          <li>Your access to or use of (or inability to access or use) the Service</li>
          <li>Any conduct or content of any third party on the Service</li>
          <li>Any content obtained from the Service, including translations</li>
          <li>
            Unauthorized access, use, or alteration of your transmissions or
            content
          </li>
        </ul>
        <p>
          IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS ARISING
          OUT OF OR RELATING TO THESE TERMS OR THE SERVICE EXCEED THE GREATER
          OF (A) THE AMOUNTS YOU HAVE PAID US IN THE TWELVE (12) MONTHS
          PRECEDING THE CLAIM, OR (B) ONE HUNDRED DOLLARS ($100).
        </p>

        <h2 id="indemnification">11. Indemnification</h2>
        <p>
          You agree to defend, indemnify, and hold harmless{" "}
          {SITE.companyName}, its affiliates, licensors, and service
          providers, and their respective officers, directors, employees,
          contractors, agents, licensors, suppliers, successors, and assigns
          from and against any claims, liabilities, damages, judgments,
          awards, losses, costs, expenses, or fees (including reasonable
          attorneys&apos; fees) arising out of or relating to your violation
          of these Terms or your use of the Service.
        </p>

        <h2 id="governing-law">12. Governing Law and Jurisdiction</h2>
        <p>
          These Terms shall be governed by and construed in accordance with
          the laws of the State of California, United States, without regard
          to its conflict-of-law provisions. Any legal action or proceeding
          arising under these Terms shall be brought exclusively in the
          federal or state courts located in San Francisco County, California,
          and you hereby consent to the personal jurisdiction and venue of
          such courts.
        </p>

        <h2 id="dispute-resolution">13. Dispute Resolution</h2>
        <p>
          Any dispute arising out of or relating to these Terms or the Service
          shall first be resolved through good-faith negotiation. If the
          dispute cannot be resolved through negotiation within thirty (30)
          days, either party may initiate binding arbitration administered by
          the American Arbitration Association in accordance with its
          Commercial Arbitration Rules. The arbitration shall be conducted in
          San Francisco, California. The arbitrator&apos;s decision shall be
          final and binding.
        </p>
        <p>
          <strong>Class Action Waiver:</strong> You agree that any dispute
          resolution proceedings will be conducted only on an individual basis
          and not in a class, consolidated, or representative action.
        </p>

        <h2 id="modifications">14. Modifications to Terms</h2>
        <p>
          We reserve the right to modify these Terms at any time. If we make
          material changes, we will notify you by updating the &quot;Last
          Updated&quot; date at the top of these Terms and, for material
          changes, by providing notice through the App or by email. Your
          continued use of the Service after such modifications constitutes
          your acceptance of the updated Terms.
        </p>

        <h2 id="termination">15. Termination</h2>
        <p>
          We may terminate or suspend your account and access to the Service
          immediately, without prior notice or liability, for any reason,
          including if you breach these Terms. Upon termination, your right to
          use the Service will immediately cease. All provisions of these
          Terms which by their nature should survive termination shall
          survive, including ownership provisions, warranty disclaimers,
          indemnification, and limitations of liability.
        </p>

        <h2 id="severability">16. Severability</h2>
        <p>
          If any provision of these Terms is held to be unenforceable or
          invalid, such provision will be changed and interpreted to
          accomplish the objectives of such provision to the greatest extent
          possible under applicable law, and the remaining provisions will
          continue in full force and effect.
        </p>

        <h2 id="entire-agreement">17. Entire Agreement</h2>
        <p>
          These Terms, together with our{" "}
          <a href="/privacy">Privacy Policy</a>, constitute the entire
          agreement between you and {SITE.companyName} regarding the Service
          and supersede all prior and contemporaneous understandings,
          agreements, representations, and warranties.
        </p>

        <h2 id="contact">18. Contact Information</h2>
        <p>
          If you have any questions about these Terms, please contact us at:
        </p>
        <ul>
          <li>
            Email:{" "}
            <a href={`mailto:${SITE.legalEmail}`}>{SITE.legalEmail}</a>
          </li>
          <li>
            Mail: {SITE.companyName}, {SITE.companyAddress}
          </li>
        </ul>
      </LegalLayout>
    </>
  );
}
